New import
git-svn-id: https://svn.ci.uchicago.edu/svn/vdl2/SwiftApps/adem-osg@2588 e2bb083e-7f23-0410-b3a8-8253ac9ef6d8

diff --git a/bin/auto-check-app b/bin/auto-check-app
--- a/bin/auto-check-app
+++ b/bin/auto-check-app
@@ -1,22 +1,28 @@
-#/bin/sh
+#/bin/bash!
+# To check on the given grid sites for the given or ALL application software or given application software deployed by the users themselves 
+#    
+
 DIR="$ADEM_HOME"
 USER=`whoami`
+CDATE=`date +%F-%R`
 i=1
 
 VO=$1
 SITE_FILE=$2
+Application=$3
 
-if [ "X$VO" == "X" ]; then
-  echo "(1)Please input the Virtual Organization name which you belong to,as the first parameter.For osg, vo can be: "
+if [ "X$VO" == "X" ] || [ "$SITE_FILE" == "" ]; then
+  echo "(1-VO)Please input the Virtual Organization name which you belong to,as the first parameter.For osg, vo can be: "
   echo "CDF CMS CompBioGrid DES DOSAR DZero Engage Fermilab fMRI GADU geant4 GLOW GPN GRASE GridChem GridEx GROW i2u2 iVDGL LIGO mariachi MIS  nanoHUB NWICG  Ops  OSG OSGEDU SDSS STAR USATLAS."
-  echo "(2)Please input the grid sites file as the second parameter.Just use a space to separate the two parameters.You can use auto-get-sites to create the available grid sites file automatically."
-  exit
-fi
-
-if [ "$SITE_FILE" == "" ]; then
-  {
-  echo "Oh,no grid sites file for the application deployment.Please input the grid sites file as the second parameter.Just use a space to separate the two parameters.You can use auto-get-sites to create the available grid sites file automatically."
-  }
+  echo "(2-Sites)Please input the grid sites file as the second parameter.Just use a space to separate the two parameters.You can use auto-get-sites to create the available grid sites file automatically."
+  echo "(3-Application)Please input the application name as the third parameter. So, you can check just one application. Otherwise, it will check all of the applications. This is optional."
+  echo "It's checking the available applications in the repository..."
+  #get the packaged application software from the Pacman cache
+  pacman -trust-all-caches -lc $REPOSITORY_HOME > $DIR/logs/deployment/package-list-$CDATE.log && PackagedSoftware=`sed -n '1!p' $DIR/logs/deployment/package-list-$CDATE.log |cut -c9- |cut -d- -f1,2 |sort -u`
+  echo "The packaged application software names include:"
+  echo "$PackagedSoftware"
+  /bin/rm -rf o..pacman..o 2>/dev/null
+  /bin/rm trusted.caches 2>/dev/null
   exit
 fi
 
@@ -26,135 +32,123 @@ do
   echo $SITE
   APP=`sed -n "$i"p $SITE_FILE | awk {'print $2'}`
   PACMAN=`sed -n "$i"p $SITE_FILE | awk {'print $3'}`
+  history=`ls $DIR/logs/deployment/pac-deploy-$SITE-*.log 2>/dev/null |wc -l`
 
-  if [ -f $DIR/tmp/pac-deploy-$SITE-out.log ]; then
+  if [ $history -gt 0 ]; then
    {
-   #make a timestamp for the deployment log
+   #make a timestamp for the log
    #echo "It is NOT the first time to query."
-   echo "`date`" >>$DIR/tmp/pac-deploy-$SITE-out.log
-   echo "`date`" >>$DIR/tmp/pac-deploy-$SITE-err.log
-   globus-job-run  $SITE  /bin/sh $APP/$VO/$USER/pac-$SITE.sh 1>>$DIR/tmp/pac-deploy-$SITE-out.log 2>>$DIR/tmp/pac-deploy-$SITE-err.log &
+   echo "`date`" >$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log
+   echo "`date`" >$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-err.log
+   globus-job-run  $SITE  /bin/sh $APP/$VO/$USER/pac-$SITE.sh 1>>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log 2>>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-err.log && echo "Check Ending `date`" >>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log || echo "Check Failed `date`" >>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log &
    }
   else
   {
   #echo "It is a new query!"
   # To create the pacman check script
-  echo "#/bin/sh" >> $DIR/tmp/pac-$SITE.sh
+  echo "#/bin/sh" > $DIR/tmp/pac-$SITE.sh
   echo "cd  $APP/$VO/$USER/work-pac"  >> $DIR/tmp/pac-$SITE.sh
   echo "source $PACMAN/setup.sh"  >> $DIR/tmp/pac-$SITE.sh
   echo "$PACMAN/bin/pacman -clear-lock" >> $DIR/tmp/pac-$SITE.sh
   echo "$PACMAN/bin/pacman -l" >> $DIR/tmp/pac-$SITE.sh
 
   # create the log file
-  echo "On $SITE,The deployment directory is: $APP/$VO/$USER/work-pac" >>$DIR/tmp/pac-deploy-$SITE-out.log
-  #make a timestamp for the deployment log
-  echo "`date`" >>$DIR/tmp/pac-deploy-$SITE-out.log
-  echo "`date`" >>$DIR/tmp/pac-deploy-$SITE-err.log
+  echo "On $SITE,The deployment directory is: $APP/$VO/$USER/work-pac" >$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log
+  #make a timestamp for the log
+  echo "`date`" >>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log
+  echo "`date`" >$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-err.log
 
   # To transmit and execute the pacman list script to the given grid site
   #globus-job-run  $SITE  -stage $DIR/tmp/pac-$SITE.sh
-  globus-url-copy  file://$DIR/tmp/pac-$SITE.sh  gsiftp://$SITE$APP/$VO/$USER/pac-$SITE.sh && globus-job-run  $SITE  /bin/sh $APP/$VO/$USER/pac-$SITE.sh 1>>$DIR/tmp/pac-deploy-$SITE-out.log 2>>$DIR/tmp/pac-deploy-$SITE-err.log &
+  globus-url-copy  file://$DIR/tmp/pac-$SITE.sh  gsiftp://$SITE$APP/$VO/$USER/pac-$SITE.sh 2>>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-err.log && globus-job-run  $SITE  /bin/sh $APP/$VO/$USER/pac-$SITE.sh 1>>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log 2>>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-err.log  && echo "Check Ending `date`" >>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log || echo "Check Failed `date`" >>$DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log &
 
-  #to delete the tempory deploy file
+  #to delete the tempory check file
   #/bin/rm -f $DIR/tmp/pac-$SITE.sh
   }
   fi
   i=`expr $i + 1` 
 done
 
-echo "Please see the deployed applications in $DIR/tmp/pac-deploy-SITE-out.log, and any error messages in $DIR/tmp/pac-deploy-SITE-err.log"
-echo "Pleas wait a minute. Now, it is creating the tc.data file..."
 sleep 60
 
-echo "#sitename	transformation	path	INSTALLED	platform	profiles" > $DIR/swift-execution-example/swift-app-tc.data
+#To check the given application
+if [ "X$Application" != "X" ]; then
+   echo "#$Application deployment successful results" > $DIR/logs/deployment/$Application-deploy-$CDATE-suc-results.log
+   echo "#$Application deployment failed results" > $DIR/logs/deployment/$Application-deploy-$CDATE-failed-results.log
+   k=1
+   for kSITE in $(awk '{print $1}' $SITE_FILE)
+   do
+     Name=`sed -n "$k"p $SITE_FILE | awk {'print $7'}`
+     SucA=`/bin/cat $DIR/logs/deployment/pac-deploy-$kSITE-$CDATE-out.log |grep \* |grep $Application`
+     if [ "X$SucA" != "X" ]; then
+        {
+        echo "#"  >>  $DIR/logs/deployment/$Application-deploy-$CDATE-suc-results.log
+        echo "#" "[$k]" "$Name" >> $DIR/logs/deployment/$Application-deploy-$CDATE-suc-results.log
+        echo "#" "$kSITE" >> $DIR/logs/deployment/$Application-deploy-$CDATE-suc-results.log
+        echo $SucA >> $DIR/logs/deployment/$Application-deploy-$CDATE-suc-results.log
+       
+        NewA=`/bin/grep $kSITE $DIR/logs/applications/$Application-deploy-succ-all-results.log 2>/dev/null`
+        if [ "X$NewA" == "X" ]; then
+           {
+           echo "#"  >> $DIR/logs/applications/$Application-deploy-succ-all-results.log
+           echo "#" "[$k]" "$Name" >> $DIR/logs/applications/$Application-deploy-succ-all-results.log
+           echo "#" "$kSITE" >> $DIR/logs/applications/$Application-deploy-succ-all-results.log
+           echo "#" "$CDATE" >> $DIR/logs/applications/$Application-deploy-succ-all-results.log
+           echo $SucA >> $DIR/logs/applications/$Application-deploy-succ-all-results.log
+           }
+        fi
+        }
+     fi
+
+     FailA=`/bin/cat $DIR/logs/deployment/pac-deploy-$kSITE-$CDATE-out.log |grep \X |grep $Application`
+     if [ "X$FailA" != "X" ]; then
+        {
+        echo "#"  >>  $DIR/logs/deployment/$Application-deploy-$CDATE-failed-results.log
+        echo "#" "[$k]" "$Name" >> $DIR/logs/deployment/$Application-deploy-$CDATE-failed-results.log
+        echo "#" "$kSITE" >> $DIR/logs/deployment/$Application-deploy-$CDATE-failed-results.log
+        echo $FailA >> $DIR/logs/deployment/$Application-deploy-$CDATE-failed-results.log
+        
+        NewF=`/bin/grep $kSITE $DIR/logs/applications/$Application-deploy-fail-all-results.log 2>/dev/null`
+        if [ "X$NewF" == "X" ]; then
+           {
+           echo "#"  >> $DIR/logs/applications/$Application-deploy-fail-all-results.log
+           echo "#" "[$k]" "$Name" >> $DIR/logs/applications/$Application-deploy-fail-all-results.log
+           echo "#" "$kSITE" >> $DIR/logs/applications/$Application-deploy-fail-all-results.log
+           echo "#" "$CDATE" >> $DIR/logs/applications/$Application-deploy-fail-all-results.log
+           echo $FailA >> $DIR/logs/applications/$Application-deploy-fail-all-results.log
+           }
+        fi
+        }
+     fi
+      k=`expr $k + 1`
+    done
+echo "The application $Application deployment successful results on all of the available grid sites are in: $DIR/logs/deployment/$Application-deploy-$CDATE-suc-results.log"
+echo "The application $Application deployment failed results on all of the available grid sites are in: $DIR/logs/deployment/$Application-deploy-$CDATE-failed-results.log"
+
+else
+#To merge the deployed application  software information on all of the available grid sites
+    echo "#Successful deployment results" > $DIR/logs/deployment/All-app-deploy-$CDATE-suc-results.log
+    echo "#Failed deployment results" > $DIR/logs/deployment/All-app-deploy-$CDATE-failed-results.log
 j=1
 for SITE in $(awk '{print $1}' $SITE_FILE)
 do
-  echo "#"  >>  $DIR/swift-execution-example/swift-app-tc.data
-  echo "#" "[$j]" "$SITE" >> $DIR/swift-execution-example/swift-app-tc.data
-  echo "#"  >>  $DIR/swift-execution-example/swift-app-tc.data
-  APP=`sed -n "$j"p $SITE_FILE | awk {'print $2'}`
-  PACMAN=`sed -n "$j"p $SITE_FILE | awk {'print $3'}`
+
   Name=`sed -n "$j"p $SITE_FILE | awk {'print $7'}`
+  echo "#"  >>  $DIR/logs/deployment/All-app-deploy-$CDATE-suc-results.log
+  echo "#" "[$j]" "$Name" >> $DIR/logs/deployment/All-app-deploy-$CDATE-suc-results.log
+  echo "#" "$SITE" >> $DIR/logs/deployment/All-app-deploy-$CDATE-suc-results.log
+  /bin/cat $DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log |grep \* >> $DIR/logs/deployment/All-app-deploy-$CDATE-suc-results.log
 
-  afni=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep afni`
-  if [ "$afni" != "" ] ; then
-  {
-   echo "$Name	afni	$APP/$VO/$USER/work-pac/afni_src/?	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-  }
-  fi
-
-  angle=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep angle`
-  if [ "$angle" != "" ] ; then
-  {
-   echo "Name	angle.sh	$APP/$VO/$USER/work-pac/angle/bin/angle.sh	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-  }
-  fi
-
-  R=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep R`
-  if [ "X$R" != "X" ] ; then
-  {
-   echo "$Name	R	$APP/$VO/$USER/work-pac/R-2.5.1/bin/R	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-  }
-  fi
-
-  dock=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep dock`
-  if [ "$dock" != "" ] ; then
-  {
-   echo "$Name	dock6	$APP/$VO/$USER/work-pac/dock6/bin/dock6	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-  }
-  fi
-
-  freesurfer=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep freesurfer`
-  if [ "$freesurfer" != "" ] ; then
-  {
-   echo "$Name	freesurfer	$APP/$VO/$USER/work-pac/freesurfer/bin/freesurfer	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-  }
-  fi
-
-  gaussian=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep gaussian`
-  if [ "$gaussian" != "" ] ; then
-  {
-   echo "$Name	g03	$APP/$VO/$USER/work-pac/gaussian/bin/g03	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-  }
-  fi
-
-  blast=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep blast-`
-  if [ "X$blast" != "X" ] ; then
-  {
-   echo "$Name	blastall	$APP/$VO/$USER/work-pac/blast-2.2.10/bin/blastall	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-   echo "$Name	formatdb	$APP/$VO/$USER/work-pac/blast-2.2.10/bin/formatdb	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-   }
-  fi
-
-  mpiblast=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep mpiblast`
-  if [ "$mpiblast" != "" ] ; then
-  {
-   echo "$Name	mpiblast	$APP/$VO/$USER/work-pac/mpiblast-1.5.0-pio/bin/mpiblast	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-   }
-  fi
-
-  nab=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep nab`
-  if [ "$nab" != "" ] ; then
-  {
-  echo "$Name	nab	$APP/$VO/$USER/work-pac/nab-5.1.2/bin/nab	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-  }
-  fi
-
-  octave=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep octave`
-  if [ "$octave" != "" ] ; then
-  {
-   echo "$Name	octave	$APP/$VO/$USER/work-pac/octave-3.0.1/bin/octave	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-   }
-  fi
-
-  oops=`/bin/cat $DIR/tmp/pac-deploy-$SITE-out.log |grep \* |grep OOPS`
-  if [ "$oops" != "" ] ; then
-  {
-   echo "$Name	oops	$APP/$VO/$USER/work-pac/clOOPS-0.9.6-BETA1-src/bin/oops	INSTALLED	INTEL32::LINUX	null" >> $DIR/swift-execution-example/swift-app-tc.data
-  }
-  fi
+  echo "#"  >> $DIR/logs/deployment/All-app-deploy-$CDATE-failed-results.log
+  echo "#" "[$j]" "$Name" >> $DIR/logs/deployment/All-app-deploy-$CDATE-failed-results.log
+  echo "#" "$SITE" >> $DIR/logs/deployment/All-app-deploy-$CDATE-failed-results.log
+  /bin/cat $DIR/logs/deployment/pac-deploy-$SITE-$CDATE-out.log |grep \X >> $DIR/logs/deployment/All-app-deploy-$CDATE-failed-results.log
 
   j=`expr $j + 1`
 done
-echo "The tc.data file for the application software executables is $DIR/swift-execution-example/swift-app-tc.data"
+echo "The deployment successful results for all the applications on all of the available grid sites are in: $DIR/logs/deployment/All-app-deploy-$CDATE-suc-results.log"
+echo "The failed results for all the applications on all of the available grid sites are in: $DIR/logs/deployment/All-app-deploy-$CDATE-failed-results.log"
+fi
+
+#To recored the command into the commands log file
+echo "$CDATE auto-check-app $VO $SITE_FILE $Application" >> $DIR/logs/commands
